# Generated by Django 6.0.1 on 2026-01-19 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_address', models.CharField(max_length=255, unique=True)),
                ('project_url', models.URLField(blank=True, max_length=500, null=True)),
                ('project_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('apartment_specific_address', models.CharField(blank=True, max_length=255)),
                ('apartment_size_sqm', models.FloatField(blank=True, null=True)),
                ('number_of_rooms', models.FloatField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('facade', models.CharField(blank=True, max_length=50, null=True)),
                ('balcony_size_sqm', models.FloatField(blank=True, null=True)),
                ('air_directions', models.CharField(blank=True, max_length=255, null=True)),
                ('parking', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('apartment_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bank_escort', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='core.project')),
            ],
        ),
    ]
