# Generated by Django 6.0.1 on 2026-01-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_apartment_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='type',
            field=models.CharField(blank=True, default='תמ"א', max_length=50, null=True),
        ),
    ]
