# Generated by Django 6.0.1 on 2026-01-21 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_profile_image_url_user_avatar_and_more'),
        ('core', '0004_deal_dealdocument_notifications_userfavorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='accounts.user'),
        ),
    ]
