# Generated by Django 6.0.1 on 2026-01-21 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_deal_user_alter_notifications_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavorites',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userfavorites',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.project'),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.apartment'),
        ),
    ]
