# Generated by Django 6.0.1 on 2026-02-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_latitude_project_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='apartment_documents/')),
                ('doc_type', models.CharField(choices=[('MAIN', 'תמונה ראשית'), ('IMAGE', 'תמונות'), ('PDF', 'קבצי pdf')], default='IMAGE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='main_image_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.apartmentdocument'),
        ),
    ]
