# Generated by Django 6.0.1 on 2026-02-01 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_apartmentdocument_apartment_main_image_doc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='start_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='dealdocument',
            old_name='document_name',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='dealdocument',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='dealdocument',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='dealdocument',
            name='status',
        ),
        migrations.AddField(
            model_name='deal',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='core.project'),
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='deal_documents/'),
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='file_type',
            field=models.CharField(choices=[('ID', 'תעודת זהות'), ('CONTRACT', 'חוזה'), ('PAYMENT', 'אישור תשלום'), ('OTHER', 'אחר')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('Active', 'פעיל'), ('Completed', 'הושלם'), ('Cancelled', 'בוטל')], default='Active', max_length=20),
        ),
    ]
