# Generated by Django 6.0.1 on 2026-02-01 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_start_date_deal_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('INITIAL', 'התחלתי'), ('IN_PROGRESS', 'בתהליך'), ('PENDING', 'ממתין'), ('COMPLETED', 'הושלם'), ('CANCELLED', 'בוטל')], default='INITIAL', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.deal')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.dealdocument')),
            ],
        ),
    ]
