# Generated by Django 6.0.1 on 2026-02-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dealtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealtransaction',
            name='status',
            field=models.CharField(choices=[('WAITING_CLIENT', 'ממתין ללקוח'), ('WAITING_APPROVAL', 'ממתין לאישור'), ('DONE', 'בוצע')], default='WAITING_CLIENT', max_length=20),
        ),
    ]
