# Generated by Django 6.0.1 on 2026-03-22 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_projectdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('ATTACHMENT', 'הצמדה'), ('CONTRACT', 'חוזה'), ('SIGNING', 'חתימה'), ('CLOSING', 'סגירה')], default='ATTACHMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='signature_image',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='signed_documents/'),
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='signing_status',
            field=models.CharField(choices=[('NONE', 'No signature required'), ('PENDING', 'Pending signature'), ('SIGNED', 'Signed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifications',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.deal'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('PAYMENT', 'Payment'), ('STAGE', 'Stage'), ('GENERAL', 'General')], default='GENERAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='dealtransaction',
            name='stage',
            field=models.CharField(choices=[('ATTACHMENT', 'הצמדה'), ('CONTRACT', 'חוזה'), ('SIGNING', 'חתימה'), ('CLOSING', 'סגירה')], default='INITIAL', max_length=20),
        ),
        migrations.CreateModel(
            name='DealTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DEAL_MANAGER', 'Deal Manager'), ('LAWYER', 'Lawyer')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('pending', 'Pending'), ('paid', 'Paid')], default='upcoming', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.deal')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
