# Generated by Django 6.0.1 on 2026-03-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_deal_stage_dealdocument_signature_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealtransaction',
            name='stage',
            field=models.CharField(choices=[('ATTACHMENT', 'הצמדה'), ('CONTRACT', 'חוזה'), ('SIGNING', 'חתימה'), ('CLOSING', 'סגירה')], default='ATTACHMENT', max_length=20),
        ),
    ]
